<?xml version="1.0" encoding="iso-8859-1"?>

<Workspace>
  <ConfigDictionary>
    
  <CurrentConfigs><Project>R3/Debug</Project></CurrentConfigs></ConfigDictionary>
  <Desktop>
    <Static>
      <Workspace>
        <ColumnWidths>
          
          
          
          
        <Column0>135</Column0><Column1>27</Column1><Column2>27</Column2><Column3>27</Column3></ColumnWidths>
      </Workspace>
    <Build><ColumnWidth0>20</ColumnWidth0><ColumnWidth1>723</ColumnWidth1><ColumnWidth2>193</ColumnWidth2><ColumnWidth3>48</ColumnWidth3></Build><TerminalIO/><Profiling/><Debug-Log><ColumnWidth0>21</ColumnWidth0><ColumnWidth1>1220</ColumnWidth1></Debug-Log><Disassembly><MixedMode>1</MixedMode><CodeCovShow>0</CodeCovShow></Disassembly></Static>
    <Windows>
      
    <Wnd2>
        <Tabs>
          <Tab>
            <Identity>TabID-4213-5518</Identity>
            <TabName>Workspace</TabName>
            <Factory>Workspace</Factory>
            <Session>
              
            <NodeDict><ExpandedNode>R3</ExpandedNode><ExpandedNode>R3/main.c</ExpandedNode><ExpandedNode>R3/main.c/Output</ExpandedNode></NodeDict></Session>
          </Tab>
        </Tabs>
        
      <SelectedTab>0</SelectedTab></Wnd2><Wnd3><Tabs><Tab><Identity>TabID-6743-8336</Identity><TabName>Build</TabName><Factory>Build</Factory><Session/></Tab><Tab><Identity>TabID-17486-16287</Identity><TabName>Debug Log</TabName><Factory>Debug-Log</Factory><Session/></Tab></Tabs><SelectedTab>0</SelectedTab></Wnd3></Windows>
    <Editor>
      
      
      
      
    <Pane><Tab><Factory>TextEditor</Factory><Filename>$WS_DIR$\main.c</Filename><XPos>0</XPos><YPos>0</YPos><SelStart>235</SelStart><SelEnd>235</SelEnd></Tab><ActiveTab>0</ActiveTab></Pane><ActivePane>0</ActivePane><Sizes><Pane><X>1000000</X><Y>1000000</Y></Pane></Sizes><SplitMode>1</SplitMode></Editor>
    <Positions>
      
      
      
      
      
    <Top><Row0><Sizes><Toolbar-00a7b0c0><key>iaridepm.enu1</key></Toolbar-00a7b0c0></Sizes></Row0></Top><Left><Row0><Sizes><Wnd2><Rect><Top>-2</Top><Left>-2</Left><Bottom>578</Bottom><Right>209</Right><x>-2</x><y>-2</y><xscreen>138</xscreen><yscreen>99</yscreen><sizeHorzCX>107813</sizeHorzCX><sizeHorzCY>137500</sizeHorzCY><sizeVertCX>164844</sizeVertCX><sizeVertCY>805556</sizeVertCY></Rect></Wnd2></Sizes></Row0></Left><Right><Row0><Sizes/></Row0></Right><Bottom><Row0><Sizes><Wnd3><Rect><Top>-2</Top><Left>-2</Left><Bottom>97</Bottom><Right>1282</Right><x>-2</x><y>-2</y><xscreen>1284</xscreen><yscreen>99</yscreen><sizeHorzCX>1003125</sizeHorzCX><sizeHorzCY>137500</sizeHorzCY><sizeVertCX>107813</sizeVertCX><sizeVertCY>137500</sizeVertCY></Rect></Wnd3></Sizes></Row0></Bottom><Float><Sizes/></Float></Positions>
  </Desktop>
</Workspace>


