<?xml version="1.0" encoding="iso-8859-1"?>

<Workspace>
  <ConfigDictionary>
    
  <CurrentConfigs><Project>R2/Debug</Project></CurrentConfigs></ConfigDictionary>
  <Desktop>
    <Static>
      <Workspace>
        <ColumnWidths>
          
          
          
          
        <Column0>124</Column0><Column1>27</Column1><Column2>27</Column2><Column3>27</Column3></ColumnWidths>
      </Workspace>
      <Build>
        
        
        
        
      <ColumnWidth0>20</ColumnWidth0><ColumnWidth1>915</ColumnWidth1><ColumnWidth2>244</ColumnWidth2><ColumnWidth3>61</ColumnWidth3></Build>
      <TerminalIO/>
      <Profiling/>
    <Debug-Log><ColumnWidth0>20</ColumnWidth0><ColumnWidth1>1221</ColumnWidth1></Debug-Log><Disassembly><MixedMode>1</MixedMode><CodeCovShow>0</CodeCovShow><InstrProfShow>0</InstrProfShow></Disassembly></Static>
    <Windows>
      
      
    <Wnd0>
        <Tabs>
          <Tab>
            <Identity>TabID-14952-21664</Identity>
            <TabName>Workspace</TabName>
            <Factory>Workspace</Factory>
            <Session>
              
            <NodeDict><ExpandedNode>R2</ExpandedNode><ExpandedNode>R2/main.c</ExpandedNode></NodeDict></Session>
          </Tab>
        </Tabs>
        
      <SelectedTab>0</SelectedTab></Wnd0><Wnd1>
        <Tabs>
          <Tab>
            <Identity>TabID-29653-21798</Identity>
            <TabName>Build</TabName>
            <Factory>Build</Factory>
            <Session/>
          </Tab>
        <Tab><Identity>TabID-20003-21141</Identity><TabName>Debug Log</TabName><Factory>Debug-Log</Factory><Session/></Tab></Tabs>
        
      <SelectedTab>0</SelectedTab></Wnd1></Windows>
    <Editor>
      
      
      
      
    <Pane><Tab><Factory>TextEditor</Factory><Filename>$WS_DIR$\main.c</Filename><XPos>0</XPos><YPos>69</YPos><SelStart>483</SelStart><SelEnd>483</SelEnd></Tab><Tab><Factory>TextEditor</Factory><Filename>$WS_DIR$\Keypad.h</Filename><XPos>0</XPos><YPos>0</YPos><SelStart>0</SelStart><SelEnd>0</SelEnd></Tab><Tab><Factory>TextEditor</Factory><Filename>$WS_DIR$\Keypad.c</Filename><XPos>3</XPos><YPos>6</YPos><SelStart>377</SelStart><SelEnd>377</SelEnd></Tab><ActiveTab>2</ActiveTab></Pane><ActivePane>0</ActivePane><Sizes><Pane><X>1000000</X><Y>1000000</Y></Pane></Sizes><SplitMode>1</SplitMode></Editor>
    <Positions>
      
      
      
      
      
    <Top><Row0><Sizes><Toolbar-00a7b0c0><key>iaridepm.enu1</key></Toolbar-00a7b0c0></Sizes></Row0></Top><Left><Row0><Sizes><Wnd0><Rect><Top>-2</Top><Left>-2</Left><Bottom>478</Bottom><Right>198</Right><x>-2</x><y>-2</y><xscreen>200</xscreen><yscreen>199</yscreen><sizeHorzCX>156250</sizeHorzCX><sizeHorzCY>276389</sizeHorzCY><sizeVertCX>156250</sizeVertCX><sizeVertCY>666667</sizeVertCY></Rect></Wnd0></Sizes></Row0></Left><Right><Row0><Sizes/></Row0></Right><Bottom><Row0><Sizes><Wnd1><Rect><Top>-2</Top><Left>-2</Left><Bottom>197</Bottom><Right>1282</Right><x>-2</x><y>-2</y><xscreen>1284</xscreen><yscreen>199</yscreen><sizeHorzCX>1003125</sizeHorzCX><sizeHorzCY>276389</sizeHorzCY><sizeVertCX>156250</sizeVertCX><sizeVertCY>276389</sizeVertCY></Rect></Wnd1></Sizes></Row0></Bottom><Float><Sizes/></Float></Positions>
  </Desktop>
</Workspace>


